-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgUEu7sCCy5Nlcy/B7
WKYS2sP6yAnEuhaKnBmteH3Gb6igCgYIKoZIzj0DAQehRANCAASsIqCZnFeOhqn3
yi1v42Y+jOfr7hobtyaHllI/IpOwJLruqJ2L6KUhTe2WPUugGRh8z3uL9ygYWJlt
Tz68FSxl
-----END PRIVATE KEY-----